### ISSUE TITLE
How to deal with broken resubscription requests?

### ISSUE THREAD

**Issue by dittodhole** [bazwilliams/node-upnp-subscription#1]
I have following scenario:

I am working on [upnp-scrobble](https://github.com/dittodhole/upnp-scrobble), which lets you forward plays from UPnP-devices to Last.fm.

So, during the UPnP _M-Search_ request I get my device and subscribe to the event URL of the _AVTransport_ service of a _MediaRenderer_ device.
Everything works so far.

The problem is, that when I disconnect the device from the grid and connect it again, it starts using a different port.
Now, the resubscribe mechanism kicks in and tries to post a new _SUBSCRIBE_ message to the old port.

I am not sure how I can handle this scenario - but I believe that there must be an error-handling in the interval for resubscribing (some `on.('error')` with the `http` object in the interval - line 51ff).

I am adding the log for convenience:

> [2015-11-21T19:39:05.061Z] ERROR: upnp-scrobble/8652 on PC09: connect ETIMEDOUT 192.168.1.7:59410 (err.code=ETIMEDOUT)
>    Error: connect ETIMEDOUT 192.168.1.7:59410
>        at Object.exports._errnoException (util.js:856:11)
>        at exports._exceptionWithHostPort (util.js:879:20)
>        at TCPConnectWrap.afterConnect [as oncomplete](net.js:1063:14)
> [2015-11-21T19:39:05.062Z] ERROR: upnp-scrobble/8652 on PC09: socket hang up (err.code=ECONNRESET)
>    Error: socket hang up
>        at createHangUpError (_http_client.js:209:15)
>        at Socket.socketCloseListener (_http_client.js:241:23)
>        at emitOne (events.js:82:20)
>        at Socket.emit (events.js:169:7)
>        at TCP._onclose (net.js:469:12)

**Comment by bazwilliams** [comment]
If the device has started on a different port, then it will need to be rediscovered. Presumably if it restarts, it may even receive a different IP address further necessitating a rediscovery. 

I've another library https://github.com/bazwilliams/node-ssdp which will fire an event when a device has joined the network, on which we could resubscribe using its new address and port?

**Comment by bazwilliams** [comment]
There is a bug in my library though, it should handle the device going away better and I think it should catch the HTTP response error event and unsubscribe.

**Comment by bazwilliams** [comment]
Correction, the library should emit an error event which would allow the client to decide whether to unsubscribe.

**Comment by dittodhole** [comment]
@bazwilliams actually, I am already using `node-ssdp` for discovery :) my problem is not the discovery part, but the changing IP and/or PORT for a device USN, which leads to a situation where I might not be able to stop the interval of the resubscription, as no error is emitted. thanks for clarification!

**Comment by bazwilliams** [comment]
I understand. I'll put some code in to emit the error. That way you can catch and unsubscribe. 

I'll see if I can do that in the next few days along with a decent test suite. 

Thanks for the bug report!

**Comment by dittodhole** [comment]
:+1: thanks a lot!

**Comment by bazwilliams** [comment]
I've published a new npm package with a fix and updated the README.md documenting the new events.

**Comment by dittodhole** [comment]
:+1: thanks a lot!
