### ISSUE TITLE
warning: possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by Jey-Cee** [bazwilliams/node-upnp-subscription#7]
Hi,

i use your modul to subscribe to all available devices and their states. Unfortunally i got an error that says i start to much listeners. That behavior is only happaning on Sonos service ZonePlayer when it's the first service that is subscribed. Sonos ZonePlayer has 13 channels, that could be subscribed.  If there is already an other subscription, everything is fine and all is running.

I my mind it is a timing problem. When the listener starts the first time, it would take a little while that the listener is ready. But during this time the other subscription requests are starting their own listeners. 

Here is the error code:
`(node) warning: possible EventEmitter memory leak detected. 11 started listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at portfinder.getPort (\node-upnp-subscription\index.js:20:27)
    at new Subscription (\node-upnp-subscription\index.js:123:9)
    at \main.js:992:47
    at Socket.<anonymous> (\adapter.js:1469:25)
    at Socket.onack (\socket.js:312:9)
    at Socket.onpacket (\socket.js:236:12)
    at Manager.<anonymous> (\node_modules\component-bind\index.js:21:15)
    at Manager.Emitter.emit (\node_modules\component-emitter\index.js:131:20)
    at Manager.ondecoded (\node_modules\socket.io-client\lib\manager.js:332:8)`

P.S.: Thank you for this great modul.

**Comment by bazwilliams** [comment]
Sorry for the delay getting back to you. I can see the problem is, I suspect the answer is simply to increase the maximum number of listeners. Before I do that though I'm going to see if I can simulate as a unit test. 

It might make it more useful if the value is exposed as a configurable property?

**Comment by bazwilliams** [comment]
Further investigation suggests this should probably use `once()` instead of `on()`.

**Comment by bazwilliams** [comment]
I've created a PR #8 which fixes this problem. I've also published a new npm package 1.0.6 which should solve your Sonos ZonePlayer issue.

**Comment by Jey-Cee** [comment]
Thank you for solving the Problem. I will check the New Version next Werk.
